name: jupyter-env
channels:
  - conda-forge
  - bioconda
  - main
dependencies:
  - python=3.9.7
  - biopython=1.79
  - pandas=1.3.4
  - seaborn=0.11.2
  - matplotlib=3.5.0
  - ipywidgets=7.6.5
  - nbconvert=5.6.1
  - jupyter_contrib_nbextensions=0.5.1
